### ISSUE TITLE
Splunk Upgrade is not working

### ISSUE THREAD

**Issue by tonyprinzler** [thesplunker/Splunkenizer#19] opened 2021-11-17 12:08 UTC
**Describe the bug**
After installing Splunk with version 8.2.1 via the ansible deployment, the upgrade to version is going wrong

**To Reproduce**
config: 
`---
# splunk_config.yml
plugin: splunkenizer

custom:
  ansible_port: 22
  ansible_user: labuser
  become_user: root

os:
  packages:
    - unzip
    - epel-release
    - sysstat
    - lsof
    - net-tools
  # Disable SELinux
  disable_selinux: true
  # Disable AppArmor
  disable_apparmor: true
  # Do not update /etc/hosts file
  update_hosts_file: false

virtualbox:
#  box: "centos/7" # Default
#  box: "ubuntu/xenial64"

# Splunk default settings
splunk_defaults:
  splunk_env_name: splk
  splunk_version: '8.2.3'
  splunk_admin_password: 'splunklab'
#  splunk_license_file: Splunk_Enterprise.lic
  splunk_indexes:
    - test1
    - test2

# Indexer Cluster settings
splunk_idxclusters:
  - idxc_name: idxc1
    idxc_password: splunkidxc
    idxc_replication_port: 9887
    idxc_rf: 2
    idxc_sf: 2

# Splunk hosts with its settings
splunk_hosts:
  # Cluster Master
  - name: host-8947
    roles:
      - cluster_master
      - deployment_server
      - monitoring_console
      #- license_master
    idxcluster: idxc1

  # Cluster Indexer
  - name: host-8948
    roles:
      - indexer
    idxcluster: idxc1

  # Cluster Indexer
  - name: host-8945
    roles:
      - indexer
    idxcluster: idxc1

  # Single Search Head
  - name: host-8946
    roles:
      - search_head

  # Universal Forwarder
  - name: host-8959
    roles:
      - universal_forwarder`

commands tested: 
- ansible-playbook ansible/upgrade_splunk.yml  --ask-pass --ask-become-pass
- ansible-playbook ansible/upgrade_splunk.yml --skip-tags splunk_control --ask-pass --ask-become-pass

**Expected behavior**
I expected splunk will be upgraded by the playbook
**Screenshots**

**Desktop (please complete the following information):**
 - OS: CentOS Linux release 8.5.2111
 - Ansible Version: ansible 2.9.27

**Additional context**
`TASK [splunk_software : find target version] *************************************************************************************************************************************************************************************************************************************************
fatal: [host-8947]: FAILED! => {"msg": "The conditional check 'find_target_version|default(true) is true' failed. The error was: template error while templating string: no test named 'true'. String: {% if find_target_version|default(true) is true %} True {% else %} False {% endif %}\n\nThe error appears to be in '/home/tony/Vagrant/Splunkenizer/ansible/roles/splunk_software/tasks/check_splunk_version.yml': line 31, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: find target version\n  ^ here\n"}
fatal: [host-8948]: FAILED! => {"msg": "The conditional check 'find_target_version|default(true) is true' failed. The error was: template error while templating string: no test named 'true'. String: {% if find_target_version|default(true) is true %} True {% else %} False {% endif %}\n\nThe error appears to be in '/home/tony/Vagrant/Splunkenizer/ansible/roles/splunk_software/tasks/check_splunk_version.yml': line 31, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: find target version\n  ^ here\n"}
fatal: [host-8945]: FAILED! => {"msg": "The conditional check 'find_target_version|default(true) is true' failed. The error was: template error while templating string: no test named 'true'. String: {% if find_target_version|default(true) is true %} True {% else %} False {% endif %}\n\nThe error appears to be in '/home/tony/Vagrant/Splunkenizer/ansible/roles/splunk_software/tasks/check_splunk_version.yml': line 31, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: find target version\n  ^ here\n"}
fatal: [host-8946]: FAILED! => {"msg": "The conditional check 'find_target_version|default(true) is true' failed. The error was: template error while templating string: no test named 'true'. String: {% if find_target_version|default(true) is true %} True {% else %} False {% endif %}\n\nThe error appears to be in '/home/tony/Vagrant/Splunkenizer/ansible/roles/splunk_software/tasks/check_splunk_version.yml': line 31, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: find target version\n  ^ here\n"}
fatal: [host-8959]: FAILED! => {"msg": "The conditional check 'find_target_version|default(true) is true' failed. The error was: template error while templating string: no test named 'true'. String: {% if find_target_version|default(true) is true %} True {% else %} False {% endif %}\n\nThe error appears to be in '/home/tony/Vagrant/Splunkenizer/ansible/roles/splunk_software/tasks/check_splunk_version.yml': line 31, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: find target version\n  ^ here\n"}`

**Comment by splunkenizer** [comment] 2021-11-17 12:34
Looks like the same issue of evaluating true or false in the code. So, when I fix Issue #18 this one can be fixed as well and can go through the code to find all the occurrences.

**Comment by tonyprinzler** [comment] 2021-11-17 12:36
[tony@splunkenizerv2 Splunkenizer]$ ansible-playbook /home/tony/Vagrant/Splunkenizer/ansible/roles/splunk_software/tasks/find_target_version.yml
ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  did not find expected key

The error appears to be in '/home/tony/Vagrant/Splunkenizer/ansible/roles/splunk_software/tasks/find_target_version.yml': line 36, column 11, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  fail:
    msg: "Cannot find latest splunk binaries in directory {{splunk_software}}"
          ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes. Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

**Comment by splunkenizer** [comment] 2021-11-17 12:48
sub playbooks cannot be run directly with ansible-playbook command. Because they are based on artifacts defined from the main or other sub playbook called from main. So, that's why you get the error here.

**Comment by tonyprinzler** [comment] 2021-11-17 12:51
Hi, thats true. This was a mistake by my site. But the error described came up by executing the upgrade yaml.

**Comment by splunkenizer** [comment] 2021-11-17 14:21
I could reproduce the issue. Looks like older python versions are more strict to boolean comparison. I will be able to fix that.

**Comment by splunkenizer** [comment] 2021-11-17 14:24
This will be fixed in #18 as this is a duplicate of the root cause.

**Closed as completed by splunkenizer** 2021-11-17 14:24 UTC
Labels: bug, duplicate
